services:
  proxy:
    image: nginx:1.25-alpine
    ports:
      - "8008:8008"
    restart: unless-stopped
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - centrifugo

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - user-files:/data/user-files
      - acls:/data/acls
    depends_on:
      - redis
    restart: unless-stopped
    mem_limit: 512m
    pids_limit: 512
    cpus: 2

  centrifugo:
    image: centrifugo/centrifugo:v5
    restart: unless-stopped
    volumes:
      - ./conf/centrifugo.json:/centrifugo/config.json
    command: centrifugo -c config.json
    pids_limit: 256
    mem_limit: 512m
    cpus: 1
    depends_on:
      - backend
      - redis
  redis:
    image: redis:alpine
    restart: unless-stopped
    mem_limit: 512m
    volumes:
      - redis-data:/data
volumes:
  user-files:
  acls:
  redis-data: