services:
  redis:
    image: redis:7.2.4-alpine3.19
    cpus: 2
    mem_limit: 512M
    pids_limit: 512
    volumes:
      - ./deploy/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-data:/data
    command:
      - /usr/local/etc/redis/redis.conf
    ports:
      - 127.0.0.1:6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 3s
    restart: unless-stopped
volumes:
  redis-data:
