max_width = 120
ignore = [
    "/proto"
]
format_macro_matchers = true
imports_granularity = "crate"
newline_style = "Unix"
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
