version: '2.4'

services:
  goldarn:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - files:/files
      - cache:/cache
    network_mode: host
    restart: unless-stopped
    pids_limit: 16384
    mem_limit: 4096M
    cpus: 2

  cleaner:
    image: c4tbuts4d/dedcleaner:latest
    restart: unless-stopped
    volumes:
      - files:/files
    environment:
      - DELETE_AFTER=30m
      - SLEEP=30m
      - DIRS=/files
    pids_limit: 512
    mem_limit: 256m
    cpus: 1

  cache_cleaner:
    build:
      context: cleaner
      dockerfile: Dockerfile
    volumes:
      - cache:/cache
    restart: unless-stopped
    pids_limit: 512
    mem_limit: 256m
    cpus: 1

volumes:
  files:
  cache:
