version: '2.4'

services:
  abilene-paradox:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - files:/files
      - cache:/cache
    ports:
      - 14141-15164:1337-2360
    restart: unless-stopped
    pids_limit: 16384
    mem_limit: 2048M
    cpus: 2

  cleaner:
    image: c4tbuts4d/dedcleaner:latest
    restart: unless-stopped
    volumes:
      - files:/files
    environment:
      - DELETE_AFTER=30m
      - SLEEP=30m
      - DIRS=/files
    pids_limit: 512
    mem_limit: 256m
    cpus: 1

  # cache_cleaner:
  #   build:
  #     context: cleaner
  #     dockerfile: Dockerfile
  #   volumes:
  #     - cache:/cache
  #   restart: unless-stopped
  #   pids_limit: 512
  #   mem_limit: 256m
  #   cpus: 1

volumes:
  files:
  cache:
